version: "3"

services:
  judge:
    build:
      context: './judge'
    image: te-sh/procon-judge
    container_name: projdg
    init: true
    tty: true
    volumes:
      - './judge:/judge'
      - './codes:/codes'
    command: ['./startup.sh']
  docs:
    build:
      context: './docs'
    image: te-sh/procon-docs
    container_name: prodoc
    environment:
      - GATSBY_TELEMETRY_DISABLED=1
    ports:
      - '8000:8000'
    volumes:
      - './docs:/app'
      - '/app/node_modules'
    command: ['yarn', 'start', '-H', '0.0.0.0']
